# html lang
language: zh

menuname: Yuki's blog

# ä½ çš„æ˜µç§° | Your Name
author: Echocolate

# main menu navigation
menu:
  å…³äºæˆ‘ğŸ‘€: https://echocolate.xyz/
  GitHubğŸ§¨: https://github.com/e-chocolate

topmenu:
  é¦–é¡µ: /
  å…³äº: /about

## ç½‘ç«™æè¿°
description: è®°å½•ç¾å¥½ä¹‹ç‰©

## ç½‘ç«™å…³é”®è¯ï¼šç”¨è‹±æ–‡é€—å·åˆ†å‰²
keywords: hexo,blog

## blogå¤´åƒ
img_src: https://avatars.githubusercontent.com/u/41510511?v=4

# ç½‘ç«™æ ‡é¢˜ | Title
logo_title: Yukiåšå®¢

#æ ‡è¯­ | Your Slogan
words: è®°å½•ç¾å¥½ä¹‹ç‰©

# æ»‘åŠ¨é¡¶éƒ¨æ¡†
# topmenu:
#  é¦–é¡µ  index: /
#  å…³äº  about: /about

# stylesheets loaded in the <head>
stylesheets:
  - /css/MiHoYo.css

# scripts loaded in the end of the body
scripts:
  - /js/MiHoYo.js

# è¯„è®ºç³»ç»Ÿ | Comments
## åšäº†åŸŸåé™åˆ¶ï¼Œè¯·æ”¹æˆè‡ªå·±çš„ KEY
## è‹¥å…³é—­valine è®¾ç½®enableä¸ºfalse
valine:
  enable: false
  appId:
  appKey:
